export const CONCEPTS = {
    react: [
      { title: "useState", slug: "use-state" },
      { title: "useReducer", slug: "use-reducer" },
      { title: "useEffect", slug: "use-effect" },
      { title: "useCallback", slug: "use-callback" },
      { title: "useMemo", slug: "use-memo" },
      { title: "useImperativeHandle", slug: "use-imperative-handle" },
      { title: "useTransition", slug: "use-transition" },
      { title: "useSyncExternalStore", slug: "use-sync-external-store" },
      { title: "useDeferredValue", slug: "use-deferred-value" },
      { title: "useRef", slug: "use-ref" },
      { title: "useContext", slug: "use-context" },
      { title: "Zustand", slug: "zustand" },
      { title: "Redux", slug: "redux" },
      { title: "React Query", slug: "react-query" },
      { title: "Higher Order Components", slug: "higher-order-components" },
      { title: "Render Props", slug: "render-props" },
      { title: "Component Slot", slug: "component-slot" },
      { title: "Observer Pattern", slug: "observer-pattern" },
      { title: "Factory Pattern", slug: "factory-pattern" },
      { title: "State Reducer Pattern", slug: "state-reducer-pattern" },
      { title: "Singleton Pattern", slug: "singleton-pattern" },
      { title: "Strategy Pattern", slug: "strategy-pattern" },
      { title: "Optimization Techniquest", slug: "optimization-techniquest" },
      { title: "Tree Shaking", slug: "tree-shaking" },
      { title: "Bundle Analyzer", slug: "bundle-analyzer" },
      { title: "React Portals", slug: "react-portals" },
      { title: "Jest", slug: "jest" },
      { title: "Vitest", slug: "vitest" },
      { title: "Storybook", slug: "storybook" },
      { title: "CSS in JS", slug: "css-in-js" },
      { title: "Sentry", slug: "sentry" },
      { title: "LogRocket", slug: "logrocket" },
      { title: "Microfrontends Nextjs", slug: "microfrontends-nextjs" },
      { title: "Remix", slug: "remix" },
      { title: "Astro", slug: "astro" },
      { title: "Seo en React", slug: "seo-react" },
      { title: "Seo en Nextjs", slug: "seo-nextjs" }
    ],
    javascript: [
      { title: "Promises y Async/Await", slug: "promises-y-async-await"},
      { title: "Closure", slug: "closure" },
      { title: "Callbacks", slug: "callbacks" },
      { title: "Higher Order Functions", slug: "higher-order-functions" },
      { title: "Promises", slug: "promises" },
      { title: "Promise Catch", slug: "promise-catch" },
      { title: "Async / Await", slug: "async-await" },
      { title: "Try / Catch", slug: "try-catch" },
      { title: "Event Loop", slug: "event-loop" },
      { title: "Array Methods", slug: "array-methods" },
      { title: "Destructuring", slug: "destructuring" },
      { title: "CommonJS vs ESM", slug: "commonjs-vs-esm" },
      { title: "Classes in JavaScript", slug: "classes-static-methods-getters-setters" },
      { title: "DOM Manipulation", slug: "dom-manipulation" },
      { title: "Repaints / Reflows", slug: "repaints-reflows" },
      { title: "Fetch", slug: "fetch" },
      { title: "Web Storage", slug: "web-storage" },
      { title: "Websockets", slug: "websockets" },
      { title: "Debounce, Throttle, and Lazy Loading", slug: "debounce-throttle-lazy-loading" },
    ],
  };
  